apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: gp6s0bltr-nodejs 
  janus-idp.io/tekton: gp6s0bltr-nodejs
  backstage.io/kubernetes-id: gp6s0bltr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gp6s0bltr-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml