apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gp6s0bltr-nodejs
  janus-idp.io/tekton: gp6s0bltr-nodejs
  backstage.io/kubernetes-id: gp6s0bltr-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gp6s0bltr-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
