apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: gp6s0bltr-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: gp6s0bltr-nodejs 
  name: gp6s0bltr-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: gp6s0bltr-nodejs 
